version: '3'
services:
  mediawiki:
    image: mediawiki:1.39
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./style_images/:/var/www/html/skins/Vector/common/images/
  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: 62db4f600b351483ffe76df022b70197
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
volumes:
  images:
  db:
