version: '3'
services:
  mediawiki:
    build: .
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./style_images/:/var/www/html/skins/Vector/common/images/

  database:
    image: mariadb
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: 62db4f600b351483ffe76df022b70197
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./db:/var/lib/mysql
volumes:
  images:
  db:
